{
 "title": "Fuse Online - Infrastructure - DB",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "db", "label": "Database", "query": "sampledb,syndesis" },
   {
    "name": "version",
    "query": "label_values(pg_static,version)"
   },
   { "name": "job", "query": "syndesis-db" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(pg_up{service=\"$job\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "content": "<h1><b><font color=#e68a00><center>$version</center></font></b></h1>"
  },
  {
   "title": "Max Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(pg_settings_max_connections{job=\"$job\",namespace=\"$namespace\"}[$interval])) or\nmax(max_over_time(pg_settings_max_connections{job=\"$job\",namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(pg_settings_shared_buffers_bytes{job=\"$job\",namespace=\"$namespace\"}[$interval])) or\nmax(max_over_time(pg_settings_shared_buffers_bytes{job=\"$job\",namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Disk-Page Buffers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(pg_settings_wal_buffers_bytes{job=\"$job\",namespace=\"$namespace\"}[$interval])) or\nmax(max_over_time(pg_settings_wal_buffers_bytes{job=\"$job\",namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Size for each Sort",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(pg_settings_work_mem_bytes{job=\"$job\",namespace=\"$namespace\"}[$interval])) or\nmax(max_over_time(pg_settings_work_mem_bytes{job=\"$job\",namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Disk Cache Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(pg_settings_effective_cache_size_bytes{job=\"$job\",namespace=\"$namespace\"}[$interval])) or\nmax(max_over_time(pg_settings_effective_cache_size_bytes{job=\"$job\",namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Autovacuum",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(pg_settings_autovacuum{job=\"$job\",namespace=\"$namespace\"}[$interval])) or\nmax(max_over_time(pg_settings_autovacuum{job=\"$job\",namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "PostgreSQL Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\",datname=~\"$db\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\",datname=~\"$db\"}[5m])) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\",datname=~\"$db\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\",datname=~\"$db\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(pg_stat_database_numbackends{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) by (datname) or \nmax(max_over_time(pg_stat_database_numbackends{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m])) by (datname)",
     "legendFormat": "{{datname}}"
    },
    {
     "expr": "max(max_over_time(pg_settings_max_connections{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or \nmax(max_over_time(pg_settings_max_connections{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Maximum connections"
    }
   ]
  },
  { "title": "Tuples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or \nsum(irate(pg_stat_database_tup_fetched{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Returned"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or\nsum(irate(pg_stat_database_tup_inserted{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Read Tuple Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Rows returned by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or\nsum(irate(pg_stat_database_tup_fetched{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Rows fetched by queries"
    }
   ]
  },
  {
   "title": "Tuples Changed per $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[1m])) or\nsum(irate(pg_stat_database_tup_inserted{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Rows inserted by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Rows updated by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Rows deleted by queries"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or \nsum(irate(pg_stat_database_xact_commit{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or\nsum(irate(pg_stat_database_xact_rollback{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Duration of Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(pg_stat_activity_max_tx_duration{job=\"$job\",namespace=\"$namespace\"}[$interval])) by (state) or\nmax(max_over_time(pg_stat_activity_max_tx_duration{job=\"$job\",namespace=\"$namespace\"}[5m])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Temp Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Number of Temp Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(pg_stat_database_temp_files{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) by (datname) or \nmax(max_over_time(pg_stat_database_temp_files{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m])) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Size of Temp Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(pg_stat_database_temp_bytes{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) by (datname) or \nmax(max_over_time(pg_stat_database_temp_bytes{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m])) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Conflicts & Locks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "sum(rate(pg_stat_database_deadlocks{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or \nsum(irate(pg_stat_database_deadlocks{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deadlocks",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "deadlocks",
     "expr": "sum(rate(pg_stat_database_conflicts{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or \nsum(irate(pg_stat_database_conflicts{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Conflicts",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "max(max_over_time(pg_locks_count{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) by (mode, datname) or\nmax(max_over_time(pg_locks_count{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m])) by (mode, datname)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}} - {{datname}}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Buffers & Blocks Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Operations with Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blk_read_time{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) by (datname) or\nsum(irate(pg_stat_database_blk_read_time{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m])) by (datname)",
     "legendFormat": "Read {{datname}}"
    },
    {
     "expr": "sum(rate(pg_stat_database_blk_write_time{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) by (datname) or\nsum(irate(pg_stat_database_blk_write_time{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m])) by (datname)",
     "legendFormat": "Write {{datname}}"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_alloc{job=\"$job\",namespace=\"$namespace\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_alloc{job=\"$job\",namespace=\"$namespace\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_backend_fsync{job=\"$job\",namespace=\"$namespace\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend_fsync{job=\"$job\",namespace=\"$namespace\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fsync calls by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_backend{job=\"$job\",namespace=\"$namespace\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend{job=\"$job\",namespace=\"$namespace\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written directly by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_clean{job=\"$job\",namespace=\"$namespace\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_clean{job=\"$job\",namespace=\"$namespace\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written by the background writer",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_checkpoint{job=\"$job\",namespace=\"$namespace\"}[5m]) or\nirate(pg_stat_bgwriter_buffers_checkpoint{job=\"$job\",namespace=\"$namespace\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written during checkpoints",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Canceled Queries",
   "type": "graph",
   "description": "Based on pg_stat_database_conflicts view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_bufferpin{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_bufferpin{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Pinned buffers"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_deadlock{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_deadlock{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_lock{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_lock{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Lock timeouts"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_snapshot{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_snapshot{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Old snapshots"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_tablespace{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_tablespace{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Dropped tablespaces "
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}) by (datname) /\n(sum(pg_stat_database_blks_hit{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}) by (datname) + \nsum(pg_stat_database_blks_read{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}) by (datname))",
     "legendFormat": "Cache hit rate {{datname}}"
    }
   ]
  },
  {
   "title": "Checkpoint stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time{job=\"$job\",namespace=\"$namespace\"}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_sync_time{job=\"$job\",namespace=\"$namespace\"}[5m])",
     "legendFormat": "Files Synchronization to disk"
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_write_time{job=\"$job\",namespace=\"$namespace\"}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_write_time{job=\"$job\",namespace=\"$namespace\"}[5m])",
     "legendFormat": "Written Files to disk"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(pg_database_size{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[$interval])) by (datname) or\nmax(max_over_time(pg_database_size{job=\"$job\",datname=~\"$db\",namespace=\"$namespace\"}[5m])) by (datname)",
     "legendFormat": "Database size {{datname}}"
    }
   ]
  }
 ]
}